# Generated by Django 5.1.1 on 2024-10-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание задания'),
        ),
    ]
