# Generated by Django 5.1.1 on 2024-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
    ]
