# Generated by Django 5.1.1 on 2024-10-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_todo_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dueDate',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
    ]
