# Generated by Django 5.1.1 on 2024-10-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todo_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='time',
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн задания'),
        ),
    ]
