services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
